apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: web-app-hardening-helloservice-service
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - web-app-hardening-helloservice-service.web-app-hardening.20.105.8.148.nip.io
  - web-app-hardening-helloservice-service
  http:
  - route:
    - destination:
        host: web-app-hardening-helloservice-service-canary.web-app-hardening.svc.cluster.local
    - destination:
        host: web-app-hardening-helloservice-service-primary.web-app-hardening.svc.cluster.local
      weight: 100
